### ISSUE TITLE
Provide a mechanism to fail a test in case a server crashes

### ISSUE THREAD

**Issue by ljacomet** [Terracotta-OSS/galvan#121]
Currently when running a Galvan test, if the server crashes there is no _automatic_ test failure and you end up waiting for ever or having to place a timeout on the test.

This would of course _not_ apply to requested server crashes.

**Comment by myronkscott** [comment]
We also need a way to detect ZAPs both wanted and unwanted.  Not sure the best way to handle it.

**Comment by myronkscott** [comment]
I believe this to be a  problem with BasicExternalCluster in the galvan-support module.  I will move this item there.  It will be somewhat difficult to support since a failure in the Rule is not perfectly aligned with the test itself but we can make the situation better.
