### ISSUE TITLE
Add support for providing server <tc-properties> members

### ISSUE THREAD

**Issue by cljohnso** [Terracotta-OSS/galvan#159]
Currently, `org.terracotta.testing.master.ConfigBuilder#buildConfig` stubs out the `<tc-properties>` configuration file element and `org.terracotta.testing.master.ServerProcess#start` only picks up JVM options from the `JVM_OPTS` environment variable.  This leaves one with no way to set a server-side property to influence server operation during a test.  It'd be nice to open up access to providing `<tc-properties>` elements and/or `JVM_OPTS` content so server options can be provided.

(Use case -- want to set `com.tc.server.entity.processor.threads` for a specific test.)

**Comment by ramsai1729** [comment]
one way to override tc.properties by placing a file named "tc.properties" with override properties in "${tc-kit}/server/lib" but I think support for overriding tc properties using galvan would be helpful, will work on this.
