### ISSUE TITLE
harness hangs in case server is crashed while it was restarted

### ISSUE THREAD

**Issue by yafeldman** [Terracotta-OSS/galvan#22]
Not every server crash is causing harness hang. This particular issue is reproducible after server is restarted and NullPointerException is thrown in PassiveServerEntity.loadExisting() API.

**Comment by yafeldman** [comment]
The hanging is coming from the IClusterControl.waitForActive() . Here is original code:
--------------------------------
   control.restartActive();
   control.waitForActive();
-----------------------------------

and once restartActive() fails waitForActive() is waiting forever.

**Comment by jd0-sag** [comment]
Is this problem still present or was it fixed along with #16?

**Comment by yafeldman** [comment]
Verified. It is not reproducible after latest galvan release.
