### ISSUE TITLE
Support starting TC server on Windows

### ISSUE THREAD

**Issue by jd0-sag** [Terracotta-OSS/galvan#23]
The Windows build of terracotta-kit now includes a batch file for starting the server so we need to add the corresponding support to Galvan to find this script.

I suspect that there are 2 parts to this:

* First of all, we need to search for the other file in the place where we otherwise search for start-tc-server.sh
* Secondly, we need need to change our use of ServerProcess.isScriptReady:  This currently waits on an event from the start-tc-server.sh script to know that the sub-process is running.  It sounds like we may not need this, on Windows, so we probably want to only wait for that on non-Windows platforms

**Comment by jd0-sag** [comment]
@esebasti This is what I mentioned in today's scrum.  Let me know if you think it would be better handled by someone else or if you have any questions.

**Comment by esebasti** [comment]
Closed https://github.com/Terracotta-OSS/galvan/pull/25
