### ISSUE TITLE
orphan process runs after test is executed and exited

### ISSUE THREAD

**Issue by yafeldman** [Terracotta-OSS/galvan#24]
org.terracotta.testing.client.TestClientStub process runs even after server is crashed and test is exited. The server is crashed when setup client is creating server side entity.
Attached are test output and server log and setup client log.

[test.out.txt](https://github.com/Terracotta-OSS/galvan/files/247847/test.out.txt)

[setup_client.log.txt](https://github.com/Terracotta-OSS/galvan/files/247851/setup_client.log.txt)
[terracotta-server.log.txt](https://github.com/Terracotta-OSS/galvan/files/247852/terracotta-server.log.txt)

**Comment by yafeldman** [comment]
The issue is in  InterruptableClientManager.java in lines:
--------------------------------------------------------------------------
     // We can only be interrupted if an interruption is expected.
      Assert.assertTrue(this.interruptRequested);
-----------------------------------------------------------------------------

where Assert is failing and due to default exception handler there is no Assert stack trace.

**Comment by jd0-sag** [comment]
Is this problem still present or was it fixed along with #16?

**Comment by yafeldman** [comment]
Verified. This issue is not reproducible.
