### ISSUE TITLE
Per-test use of BasicExternalCluster spawns threads without cleanup

### ISSUE THREAD

**Issue by cljohnso** [Terracotta-OSS/galvan#35]
A thread dump taken while running an Ehcache JUnit test with 8 test methods and using per-test `BasicExternalCluster` seems to show a number of threads are not being "retired" when the server cluster is being terminated using explicit `Cluster.getClusterControl().tearDown()` calls.  

Do the tests need to do something else to clean up the environment between tests?

---

The thread dump may be found at [galvan_thread_dump_8_tests.txt](https://github.com/Terracotta-OSS/galvan/files/320952/galvan_thread_dump_8_tests.txt).

The preamble of the test class includes:

``` java
  @Rule
  public final TestName testName = new TestName();

  @Rule
  public final Cluster cluster =
      new BasicExternalCluster(new File("build/cluster"), 1, Collections.<File>emptyList(), "", RESOURCE_CONFIG, null);

  @Before
  public void waitForActive() throws Exception {
    cluster.getClusterControl().waitForActive();
  }
```

Each test includes

```
    cluster.getClusterControl().tearDown();
```

The stack trace show 8 copies of several threads including
- `L1_L2:TCComm Main Selector Thread_W`
- `L1_L2:TCComm Main Selector Thread_R`
- `Out of band notifier - Main`
- `SampledCounterManager Timer`
- `task-runner-thread-0`
- `WorkerThread(client_coordination_stage, 0)`
- `WorkerThread(cluster_events_stage, 0)`

and a bunch of others.

**Comment by jd0-sag** [comment]
We will need to re-test this on the release version since some changes around client-side threads have touched on this.

**Comment by cljohnso** [comment]
Still have a fair number of threads apparently not being disposed of ... see 
[threadDump_2016Nov14.txt](https://github.com/Terracotta-OSS/galvan/files/589471/threadDump_2016Nov14.txt).

----

The thread dump can be replicated by amending a test class in Ehcache3 and running the test.  

The target class is `org.ehcache.clustered.TerminatedServerTest` in `clustered/integration-test`.  Add the following _after_ the `org.ehcache.clustered.TerminatedServerTest#restoreProperties` method:

```java
  @AfterClass
  public static void takeThreadDump() {
    Diagnostics.threadDump();
  }
```

Run the `TerminatedServerTest` class using:

```bash
./gradlew -D:clustered:integration-test:test.single=TerminatedServerTest :clustered:integration-test:test
```
 and look at the thread dump found in `clustered/integration-test/build/test-results/test/TEST-org.ehcache.clustered.TerminatedServerTest.xml`.

**Comment by jd0-sag** [comment]
These threads aren't related to Galvan, but the client-side logic in the test, itself.

Either the test isn't shutting down EhCache, EhCache isn't properly bringing down the connection, or the connection isn't correctly shutting down.
