### ISSUE TITLE
windows bug.  Invalid characters in file path cause tests to fail

### ISSUE THREAD

**Issue by gibsong** [Terracotta-OSS/galvan#61]
There is a windows bug which was first noticed in ehcache/ehcache3#1217
It is caused by "(" and ")" characters in a folders name.  Although "(" and ")" are valid characters in a folders name, they become a problem when you try run a a command that includes them.  These characters are initially stored in the BasicExternalCluster.displayName instance variable and are eventually used to build a file path, which is then used to invoke a command, which fails.  I believe it is trying to start up the server, and the file path gets truncated at the first occurrence of the "(".

**Comment by lorban** [comment]
Relates to https://github.com/ehcache/ehcache3/issues/1217

**Comment by jd0-sag** [comment]
Is this a galvan issue or something related to the kit start script, itself?

**Comment by gibsong** [comment]
it could be related to the kit start script.  let me test start-tc-server.bat and see if the issue is within this script.

**Comment by gibsong** [comment]
I did some more testing, and found the problem.  The issue isn't in the start script but in ServerProcess.java.  There is a String variable called startScript which for windows needs to be wrapped in double quotes.  I can submit the bug fix.

**Comment by jd0-sag** [comment]
Sounds good.  If you can figure out a good way to add another integration-test to prove that the fix works, that would also be useful.

**Comment by gibsong** [comment]
I just committed the bug fix.  Once this is merged I will push my integration-test to ehcache3.

**Comment by jd0-sag** [comment]
Can you include the test in this PR, as one of the galvan integration tests?  Since it is a test of galvan, it should really be along-side it.
